# Generated by Django 5.2.12 on 2026-04-05 11:48

import WellnessNewProject.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', validators=[WellnessNewProject.validators.MaxFileSizeValidator(5242880)]),
        ),
    ]
