# Generated by Django 5.2.12 on 2026-04-05 11:31

import WellnessNewProject.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_date_of_birth_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[WellnessNewProject.validators.MaxFileSizeValidator(5242880)]),
        ),
    ]
