# Generated by Django 5.2.12 on 2026-04-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Host', 'Host'), ('Participant', 'Participant'), ('Instructor', 'Instructor')], default='Participant', max_length=50),
        ),
    ]
