# Generated by Django 5.2.12 on 2026-04-15 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_review_review_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
