# Generated by Django 5.2.12 on 2026-04-01 12:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudioClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_title', models.CharField(max_length=100)),
                ('class_description', models.TextField()),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('All Levels', 'All Levels')], default='All Levels', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(30)])),
                ('start_time', models.TimeField()),
                ('hall_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_classes', to=settings.AUTH_USER_MODEL)),
                ('studio_class_service', models.ManyToManyField(related_name='studio_classes', to='services.service')),
                ('tags', models.ManyToManyField(related_name='studio_classes', to='studio_classes.tag')),
            ],
        ),
    ]
