# Generated by Django 5.2.12 on 2026-04-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studioclass',
            name='class_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
